---
language:
  - 'php'
  - 'python'
php:
  - "5.6"
python:
  - "2.7"
sudo: required
# services:
#   - postgresql
# addons:
#   postgresql: "9.1"
before_install:
  - git submodule update --init --recursive
  - # sudo apt-get update -qq
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y 
  - # sudo mkdir -p /etc/apache2/conf-available/
install:
  - cd $TRAVIS_BUILD_DIR
  - vagrant/install-on-travis-ci.sh

before_script:
  - cd $TRAVIS_BUILD_DIR
  - wget --no-verbose --output-document=data/monaco.osm.pbf http://download.geofabrik.de/europe/monaco-latest.osm.pbf
  - ./utils/setup.php --osm-file data/monaco.osm.pbf --osm2pgsql-cache 1000 --all 2>&1 | tee monaco.$$.log
  - ./utils/specialphrases.php --countries > data/specialphrases_countries.sql
  - psql -d nominatim -f data/specialphrases_countries.sql
script:
  - cd $TRAVIS_BUILD_DIR/tests
  - NOMINATIM_SERVER=http://localhost:8089/nominatim lettuce features
  - cd $TRAVIS_BUILD_DIR/tests-php
  - phpunit ./
