---
language:
  - 'php'
  - 'python'
php:
  - "5.6"
python:
  - "2.7"
services:
  - postgresql
# addons:
#   postgresql: "9.1"
install:
  - cd $TRAVIS_BUILD_DIR
  - echo $USER
  - echo $TRAVIS_BUILD_DIR
  - cat vagrant/install-on-ubuntu-16.sh | perl -pe's!USERNAME=(\w+)!USERNAME=$ENV{USER}!' | perl -pe's!USERHOME=(\S+)!USERHOME=$ENV{TRAVIS_BUILD_DIR}!' > install-on-travis.sh
  - chmod a+x install-on-travis.sh
  - ./install-on-travis.sh
before_script:
  - cd $TRAVIS_BUILD_DIR
  - wget --no-verbose --output-document=data/monaco.osm.pbf http://download.geofabrik.de/europe/monaco-latest.osm.pbf
  - ./utils/setup.php --osm-file data/monaco.osm.pbf --osm2pgsql-cache 1000 --all 2>&1 | tee monaco.$$.log
  - ./utils/specialphrases.php --countries > data/specialphrases_countries.sql
  - psql -d nominatim -f data/specialphrases_countries.sql
script:
  - cd $TRAVIS_BUILD_DIR/tests
  - NOMINATIM_SERVER=http://localhost:8089/nominatim lettuce features
  - cd $TRAVIS_BUILD_DIR/tests-php
  - phpunit ./
